export default {
    data:[{
        title:'问答收入',
        open:false,
        data:{
            "9月17日":[{
                info:"王豆子向您支付问答费",
                price:68
            },{
                info:"王豆子向您支付问答费",
                price:68
            }], 
            "9月18日":[{
                info:"王豆子向您支付问答费",
                price:68
            },{
                info:"王豆子向您支付问答费",
                price:68
            }]
        }
    },{
        title:'偷听收入',
        open:false,
        data:{
            "9月20日":[{
                info:"王豆子向您支付问答费",
                price:68
            },{
                info:"王豆子向您支付问答费",
                price:90
            }], 
            "9月21日":[{
                info:"王豆子向您支付问答费",
                price:68
            },{
                info:"王豆子向您支付问答费",
                price:68
            }]
        }
    },{
        title:'资料库收入',
        open:false,
        data:{
            "9月22日":[{
                info:"王豆子向您支付问答费",
                price:68
            },{
                info:"王豆子向您支付问答费",
                price:68
            }], 
            "9月23日":[{
                info:"王豆子向您支付问答费",
                price:100
            },{
                info:"王豆子向您支付问答费",
                price:68
            }]
        }
    }]
}